#include<stdio.h>
#include<stdlib.h>
main ()
{
   int a,b,c,d,e,f,g,h,i,j,k,l;
   double m,n; 
   while(scanf("%d %d %d %d",&a,&b,&c,&d)==4){
    e=a+b;
    f=c+d;
    g=a-b;
    h=c-d;
    i=a*b;
    j=c*d;
    m=(double)a/b;
    n=(double)c/d;
    if(e+f==24)
        printf("%d+%d+%d+%d\n",a,b,c,d);
    if(e*f==24)
          printf("(%d+%d)*(%d+%d)\n",a,b,c,d);
    if(e+h==24)
         printf("%d+%d+%d-%d\n",a,b,c,d);
    if(e-h==24)
         printf("%d+%d-%d+%d\n",a,b,c,d);
    if(e*h==24)
         printf("(%d+%d)*(%d-%d)\n",a,b,c,d);
    if(g+f==24)
         printf("%d-%d+%d+%d\n",a,b,c,d);
    if(g*f==24)
         printf("(%d-%d)*(%d+%d)\n",a,b,c,d);
    if(g*h==24)
         printf("(%d-%d)*(%d-%d)\n",a,b,c,d);
     if(i+f==24)
         printf("%d*%d+%d+%d\n",a,b,c,d);
    if(i-f==24)
         printf("%d*%d-%d-%d\n",a,b,c,d);
    if(i*f==24)
         printf("%d*%d*(%d+%d)\n",a,b,c,d);      
    if(f!=0&&i/f==24)
         printf("%d*%d/(%d+%d)\n",a,b,c,d);
    if(i+h==24)
         printf("%d*%d+%d-%d\n",a,b,c,d);
    if(i-h==24)
         printf("%d*%d-%d+%d\n",a,b,c,d);
    if(i*h==24)
         printf("%d*%d*(%d-%d)\n",a,b,c,d);
   if(h!=0&&i/h==24)
         printf("%d*%d/(%d-%d)\n",a,b,c,d);
    if(e+j==24)
         printf("%d+%d+%d*%d\n",a,b,c,d);
    if(e*j==24)
         printf("(%d+%d)*%d*%d\n",a,b,c,d);
    if(g+j==24)
         printf("%d-%d+%d*%d\n",a,b,c,d);
    if(g*j==24)
         printf("(%d-%d)*%d*%d\n",a,b,c,d);
    if(i+j==24)
         printf("%d*%d+%d*%d\n",a,b,c,d);
    if(i-j==24)
         printf("%d*%d-%d*%d\n",a,b,c,d); 
    if(i*j==24)
         printf("%d*%d*%d*%d\n",a,b,c,d);
    if(j!=0&&i/j==24)
         printf("%d*%d/(%d*%d)\n",a,b,c,d); 
    if(e+n==24)
         printf("%d+%d+(%d/%d)\n",a,b,c,d);
     if(d!=0&&(double)(e*c)/d==24)
         printf("(%d+%d)*%d/%d\n",a,b,c,d);
    if(c!=0&&(double)(e*d)/c==24)
         printf("(%d+%d)/(%d/%d)\n",a,b,c,d); 
    if(d!=0&&(double)(g*c)/d==24)
         printf("(%d-%d)*%d/%d\n",a,b,c,d);
    if(c!=0&&(double)(g*d)/c==24)
         printf("(%d-%d)/(%d/%d)\n",a,b,c,d);
    if(i+n==24)
         printf("%d*%d+%d/%d\n",a,b,c,d); 
    if(i-n==24)
         printf("%d*%d-%d/%d\n",a,b,c,d);
    if(d!=0&&(double)(i*c)/d==24)
         printf("%d*%d*%d/%d\n",a,b,c,d);
    if(c!=0&&(double)(i*d)/c==24)
         printf("%d*%d/(%d/%d)\n",a,b,c,d);
     if(m+f==24)
         printf("%d/%d+%d+%d\n",a,b,c,d); 
    if(b!=0&&(double)(a*f)/b==24)
         printf("%d/%d*(%d+%d)\n",a,b,c,d);
     if(b!=0&&(double)(a*h)/b==24)
         printf("%d/%d*(%d-%d)\n",a,b,c,d);
     if(m+j==24)
         printf("%d/%d+%d*%d\n",a,b,c,d);     
     if(b!=0&&(double)(a*j)/b==24)
         printf("%d/%d*%d*%d\n",a,b,c,d); 
     if(a*c/(b*d)==24)
          printf("%d/%d*%d/%d\n",a,b,c,d);   
     if(a*(b+c+d)==24)
           printf("%d*(%d+%d+%d)\n",a,b,c,d);
     if(a*(b+c-d)==24)
           printf("%d*(%d+%d-%d)\n",a,b,c,d);
     if(a+((b+c)*d)==24)
           printf("%d+(%d+%d)*%d\n",a,b,c,d);
     if(a*d*(b+c)==24)
           printf("%d*(%d+%d)*%d\n",a,b,c,d);
     if(a+(double)(b+c)/d==24)
           printf("%d+(%d+%d)/%d\n",a,b,c,d);
     if((double)(a*(b+c))/d==24)
           printf("%d*(%d+%d)/%d\n",a,b,c,d);
     if((double)(a*d)/(b+c)==24)
           printf("%d/((%d+%d)/%d)\n",a,b,c,d);
     if(a*(b-c+d)==24)
           printf("%d*(%d-%d+%d)\n",a,b,c,d);
     if(a*(b-c-d)==24)
           printf("%d*(%d-%d-%d)\n",a,b,c,d);
     if(a+(b-c)*d==24)
           printf("%d+(%d-%d)*%d\n",a,b,c,d);
     if(a-(b-c)*d==24)
           printf("%d-(%d-%d)*%d\n",a,b,c,d); 
     if(a*(b-c)*d==24)
           printf("%d*(%d-%d)*%d\n",a,b,c,d);
     if((double)(a*(b-c))/d==24) 
           printf("%d*(%d-%d)/%d\n",a,b,c,d); 
     if((double)(a*d)/(b-c)==24)
           printf("%d/((%d-%d)/%d)\n",a,b,c,d);
     if(a+(b*c)+d==24)
           printf("%d+%d*%d+%d\n",a,b,c,d);
     if(a*(b*c+d)==24)
           printf("%d*(%d*%d+%d)\n",a,b,c,d);
     if(a+b*c-d==24)
           printf("%d+%d*%d-%d\n",a,b,c,d);
     if(a*(b*c-d)==24)
           printf("%d*(%d*%d-%d)\n",a,b,c,d);
     if(a+b*c*d==24)
           printf("%d+%d*%d*%d\n",a,b,c,d);
     if(a+(double)(b*c)/d==24)
           printf("%d+%d*%d/%d\n",a,b,c,d);
     if((double)(a*d)/(b*c)==24)
           printf("%d/(%d*%d/%d)\n",a,b,c,d); 
     if((double)(b)/c+a+d==24)
           printf("%d+%d/%d+%d\n",a,b,c,d);
     if(a*d+(double)(a*b)/c==24)
           printf("%d*((%d/%d)+%d)\n",a,b,c,d);
     if((double)(a*b)/c-a*d==24)
           printf("%d*((%d/%d)-%d)\n",a,b,c,d);
     if((double)(a*c)/(b-c*d)==24)
           printf("%d/((%d/%d)-%d)\n",a,b,c,d);
     if(a+(double)(b*d)/c==24)
           printf("%d+%d/%d*%d\n",a,b,c,d);
     if((double)(a*b*d)/c==24)
           printf("%d*%d/%d*%d\n",a,b,c,d);
     if((double)(a*c)/(b*d)==24)
           printf("%d/(%d/%d*%d)\n",a,b,c,d);
     if(((double)(a*b)/c)/d==24)
           printf("%d*%d/%d/%d\n",a,b,c,d);
     if((double)(a*c*d)/b==24)
           printf("%d/(%d/%d/%d)\n",a,b,c,d);
     if(a+b*(c+d)==24)
           printf("%d+%d*(%d+%d)\n",a,b,c,d);    
     if((double)(a*(c+d))/b==24)
           printf("%d/(%d/(%d+%d))\n",a,b,c,d);
     if(a+b*(c-d)==24)
           printf("%d+%d*(%d-%d)\n",a,b,c,d);
     if(a-b*(c-d)==24)
           printf("%d-%d*(%d-%d)\n",a,b,c,d);
     if(a-b/(double)(c-d)==24)
           printf("%d-%d/(%d-%d)\n",a,b,c,d); 
     if((double)(a*(c-d))/b==24)
           printf("%d/(%d/(%d-%d))\n",a,b,c,d);
     if(a*(b+(c*d))==24)
           printf("%d*(%d+%d*%d)\n",a,b,c,d); 
     if(a*(b-c*d)==24)
           printf("%d*(%d-%d*%d)\n",a,b,c,d); 
     if((double)(a*c*d)/b==24)
            printf("%d/(%d/(%d*%d))\n",a,b,c,d);
     if(a*b+(double)(a*c)/d==24)
            printf("%d*(%d+%d/%d)\n",a,b,c,d); 
     if(a*b-(double)(a*c)/d==24)
            printf("%d*(%d-(%d/%d))\n",a,b,c,d);
     if((double)(a*d)/(b*d-c)==24)
            printf("%d/(%d-(%d/%d))\n",a,b,c,d);
     if(a+(double)(b*d)/c==24)
            printf("%d+(%d/(%d/%d))\n",a,b,c,d); 
     if((double)(a*c)/(b*d)==24)
            printf("%d/(%d/(%d/%d))\n",a,b,c,d);    
     if((a+b+c)*d==24)
            printf("(%d+%d+%d)*%d\n",a,b,c,d);
     if((double)(a+b+c)/d==24)
            printf("(%d+%d+%d)/%d\n",a,b,c,d); 
     if((a+b-c)*d==24)
            printf("(%d+%d-%d)*%d\n",a,b,c,d);
     if((double)(a+b-c)/d==24)
            printf("(%d+%d-%d)/%d\n",a,b,c,d);
     if((a+b)*c+d==24)
              printf("(%d+%d)*%d+%d\n",a,b,c,d);
     if((a+b)*c-d==24)
              printf("(%d+%d)*%d-%d\n",a,b,c,d);
     if((double)(a+b)/c+d==24)
               printf("(%d+%d)/%d+%d\n",a,b,c,d);
     if((double)(a+b)/c-d==24)
               printf("(%d+%d)/%d-%d\n",a,b,c,d);
     if(((a+b)*d)/(double)(c)==24)
               printf("(%d+%d)/%d*%d\n",a,b,c,d);
     if((a-b+c)*d==24)
               printf("(%d-%d+%d)*%d\n",a,b,c,d); 
     if((a-b-c)*d==24)
               printf("(%d-%d-%d)*%d\n",a,b,c,d); 
     if((a-b)*c+d==24)
               printf("(%d-%d)*%d+%d\n",a,b,c,d);
     if((a-b)*c-d==24)
               printf("(%d-%d)*%d-%d\n",a,b,c,d);  
     if((a*b+c)*d==24)
                printf("(%d*%d+%d)*%d\n",a,b,c,d);
     if((double)(a*b+c)/d==24)
                printf("(%d*%d+%d)/%d\n",a,b,c,d); 
     if((a*b-c)*d==24)
                printf("(%d*%d-%d)*%d\n",a,b,c,d);
     if((double)(a*b-c)/d==24)
                printf("(%d*%d-%d)/%d\n",a,b,c,d); 
      if(a*b*c+d==24)
                 printf("%d*%d*%d+%d\n",a,b,c,d); 
      if(a*b*c-d==24)
                 printf("%d*%d*%d-%d\n",a,b,c,d); 
      if((double)(a*b)/c+d==24)
                 printf("%d*%d/%d+%d\n",a,b,c,d);
      if((double)(a*b)/c-d==24)
                 printf("%d*%d/%d-%d\n",a,b,c,d);  
      if(c*d+a*d/(double)(b)==24)
                  printf("((%d/%d)+%d)*%d\n",a,b,c,d);  
      if((a+b*c)/(double)(b*d)==24)
                  printf("((%d/%d)+%d)/%d\n",a,b,c,d);  
      if(a*d/(double)(b)-c*d==24)
                  printf("((%d/%d)-%d)*%d\n",a,b,c,d);  
      if((a-b*c)/(double)(b*d)==24)
                  printf("((%d/%d)-%d)/%d\n",a,b,c,d);  
      if((double)(a*c)/b+d==24)
                   printf("%d/%d*%d+%d\n",a,b,c,d);
      if((double)(a*c)/b-d==24)
                   printf("%d/%d*%d-%d\n",a,b,c,d);     
      if((double)(a*d)/(b*c)==24)
                    printf("%d/%d/%d*%d\n",a,b,c,d);     
      if(a*(b+c)+d==24)
                    printf("%d*(%d+%d)+%d\n",a,b,c,d);
      if(a*(b+c)-d==24)
                    printf("%d*(%d+%d)-%d\n",a,b,c,d); 
      if((double)(a)/(b+c)*d==24)
                     printf("%d/(%d+%d)*%d\n",a,b,c,d);
      if(a*(b-c)+d==24)
                      printf("%d*(%d-%d)+%d\n",a,b,c,d);
      if(a*(b-c)-d==24)
                      printf("%d*(%d-%d)-%d\n",a,b,c,d);
      if((a-b*c)*d==24)
                      printf("(%d-%d*%d)*%d\n",a,b,c,d);
      if((double)(a*d)/(b*c)==24)
                      printf("%d/(%d*%d)*%d\n",a,b,c,d);
      if((double)(a*c)/b+d==24)
                      printf("%d/(%d/%d)+%d\n",a,b,c,d);
      if((double)(a*c)/b-d==24)
                      printf("%d/(%d/%d)-%d\n",a,b,c,d);
      if((double)(a*c*d)/b==24)
                      printf("%d/(%d/%d)*%d\n",a,b,c,d);
      if((double)(a*c)/(b*d)==24)
                      printf("%d/(%d/%d)/%d\n",a,b,c,d); 
    }
    return 0;
}